import { createClient, type SupabaseClient } from '@supabase/supabase-js';

import { env } from '@/config/env';

import { secureSessionStore } from './secure-session-store';

/**
 * The single Supabase client.
 *
 * §4.3: the app "must access backend capabilities through typed service interfaces so
 * individual vendors can be changed later without rewriting screens". So this module is the
 * only place `@supabase/supabase-js` is imported outside the repositories — screens never
 * see it, and swapping the vendor means rewriting the repositories, not the UI.
 *
 * The session lives in the platform keychain via `secureSessionStore`, per §13.1's
 * "SecureStore for refresh/session secrets". That adapter chunks the value because a
 * Supabase session exceeds SecureStore's practical per-value size — see its own comments.
 */
/**
 * Hand-written schema types, mirroring supabase/migrations.
 *
 * Not generated by `supabase gen types`, because that needs a live project and Milestone 1
 * has none yet. The shape below is what supabase-js expects — each table needs `Row`,
 * `Insert`, `Update` and `Relationships`, and the schema needs `Views`, `Functions`, `Enums`
 * and `CompositeTypes` — otherwise query results infer as `never` and every field access
 * fails to compile.
 *
 * Replace this file with generated types once a Supabase project exists.
 */
type ProfileRow = {
  user_id: string;
  display_name: string | null;
  avatar_path: string | null;
  status: string;
  onboarding_version: number;
  created_at: string;
  updated_at: string;
};

type StudentProfileRow = {
  user_id: string;
  provider: string | null;
  provider_other: string | null;
  campus: string | null;
  course: string | null;
  study_level: string | null;
  intake_month: number | null;
  intake_year: number | null;
  completion_month: number | null;
  completion_year: number | null;
  student_email: string | null;
  suburb: string | null;
  postcode: string | null;
  arrival_status: string | null;
  india_state_code: string | null;
  hometown: string | null;
  created_at: string;
  updated_at: string;
};

type IndiaStateRow = {
  code: string;
  name: string;
  is_union_territory: boolean;
  sort_order: number;
  active: boolean;
};

type EducationProviderRow = {
  code: string;
  name: string;
  city: string | null;
  sort_order: number;
  active: boolean;
};

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow;
        Insert: Pick<ProfileRow, 'user_id'> & Partial<Omit<ProfileRow, 'user_id'>>;
        Update: Partial<ProfileRow>;
        Relationships: [];
      };
      student_profiles: {
        Row: StudentProfileRow;
        Insert: Pick<StudentProfileRow, 'user_id'> & Partial<Omit<StudentProfileRow, 'user_id'>>;
        Update: Partial<StudentProfileRow>;
        Relationships: [];
      };
      india_states: {
        Row: IndiaStateRow;
        Insert: IndiaStateRow;
        Update: Partial<IndiaStateRow>;
        Relationships: [];
      };
      education_providers: {
        Row: EducationProviderRow;
        Insert: EducationProviderRow;
        Update: Partial<EducationProviderRow>;
        Relationships: [];
      };
    };
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};

export type KyaSceneSupabaseClient = SupabaseClient<Database>;

let client: KyaSceneSupabaseClient | undefined;

export function getSupabase(): KyaSceneSupabaseClient {
  client ??= createClient<Database>(
    env.EXPO_PUBLIC_SUPABASE_URL,
    env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {
        storage: secureSessionStore,
        autoRefreshToken: true,
        persistSession: true,
        // React Native has no URL to parse a callback out of; email OTP does not use one.
        detectSessionInUrl: false,
      },
    },
  );

  return client;
}

/** Test seam. Lets a test inject a fake without reaching into module state. */
export function __setSupabaseClientForTests(next: KyaSceneSupabaseClient | undefined): void {
  client = next;
}
