-- Milestone 3 — beta home, referrals, feedback, settings and deletion (spec §21, §S18–§S22)
--
-- §11.3 forbids creating tables ahead of the milestone that owns them, so this adds exactly
-- what S18 through S22 need and nothing for the social product.

-- ------------------------------------------------------------- feature flags

/**
 * §6.5: "Server-managed feature flags. Default every future flag to false."
 *
 * The client already carries `DEFAULT_FEATURE_FLAGS`, all false, and uses them until the
 * server answers — so a failed fetch hides features rather than revealing unfinished ones.
 * This table is the server half of that contract.
 *
 * §S18 makes it load-bearing rather than decorative: the beta home shows cards for Find
 * people, Scene feed, events, housing and jobs, and its acceptance criterion is that "no
 * disabled feature looks tappable". Whether a card is real is a server decision, so a feature
 * can be switched off after a build ships.
 */
create table public.feature_flags (
  key text primary key,
  enabled boolean not null default false,
  description text not null,
  updated_at timestamptz not null default now(),

  constraint feature_flag_key_shape check (key ~ '^[a-z][a-z0-9_]{2,63}$')
);

comment on table public.feature_flags is
  'Server-managed feature flags (§6.5). Absent or disabled both mean off; the client defaults
   to false so a failed fetch cannot reveal an unfinished feature.';

-- ----------------------------------------------------------- feature voting

/**
 * §S18: "feature-voting cards". One vote per person per feature — enforced by the primary
 * key rather than by the screen, because a screen cannot see a second device.
 *
 * `feature_key` deliberately has no foreign key to `feature_flags`. Voting is about what to
 * build next, so the interesting votes are for things that have no flag yet; a reference
 * would mean adding a row to a live configuration table in order to ask a question about it.
 */
create table public.feature_votes (
  user_id uuid not null references public.profiles (user_id) on delete cascade,
  feature_key text not null,
  created_at timestamptz not null default now(),

  primary key (user_id, feature_key),
  constraint feature_vote_key_shape check (feature_key ~ '^[a-z][a-z0-9_]{2,63}$')
);

-- ------------------------------------------------------------ announcements

/** §S18: "beta announcements". Written by operators, read by approved students. */
create table public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  published_at timestamptz not null default now(),
  active boolean not null default true,

  constraint announcement_title_length check (char_length(btrim(title)) between 1 and 120),
  constraint announcement_body_length check (char_length(btrim(body)) between 1 and 2000)
);

create index announcements_live on public.announcements (published_at desc) where active;

-- ---------------------------------------------------------------- feedback

create type public.feedback_category as enum (
  'bug',
  'confusing',
  'missing_feature',
  'safety_concern',
  'general'
);

/**
 * §S20 — structured feedback.
 *
 * `reference` is the acceptance criterion: "Submission works without an email client and
 * returns a reference number." It is generated by the database rather than the client so it
 * is unique by construction and cannot be forged into someone else's support thread.
 *
 * The comment is capped at 4000 characters. §S20 asks the screen to warn against including
 * passwords or identity documents; the cap is not a privacy control, it is a limit on what a
 * single submission can carry into an operator's queue.
 *
 * `screenshot_path` holds a storage key, never an image. §13.2's minimisation applies: the
 * object itself lives in a private bucket with its own policy.
 */
create table public.feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (user_id) on delete cascade,
  reference text not null unique,
  rating smallint,
  category public.feedback_category not null,
  comment text not null,
  screenshot_path text,
  created_at timestamptz not null default now(),

  constraint feedback_rating_range check (rating is null or rating between 1 and 5),
  constraint feedback_comment_length check (char_length(btrim(comment)) between 1 and 4000)
);

create index feedback_by_recency on public.feedback (created_at desc);

/**
 * A reference a person can read down a phone line: KYA-7F3K2Q.
 *
 * Deliberately not sequential. A counter would tell every tester how much feedback the beta
 * has received, which is commercial information given away for nothing.
 */
create or replace function public.generate_feedback_reference()
returns text
language sql
volatile
as $$
  select 'KYA-' || string_agg(
    substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', 1 + floor(random() * 32)::integer, 1),
    ''
  )
  from generate_series(1, 6);
$$;

comment on function public.generate_feedback_reference is
  'Human-readable support reference (§S20). Ambiguous characters (I, O, 0, 1) are excluded so
   it survives being read aloud or copied by hand.';

-- --------------------------------------------------------------- push tokens

/**
 * The §21.5 "push-token foundation". Registration only — Milestone 3 sends nothing.
 *
 * Unique on the token, not on the user: one person has several devices, and one device can
 * be handed to a different person. `on conflict (token)` reassigning `user_id` is what stops
 * a notification following a device to its new owner.
 */
create table public.push_tokens (
  token text primary key,
  user_id uuid not null references public.profiles (user_id) on delete cascade,
  platform text not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),

  constraint push_platform check (platform in ('ios', 'android'))
);

create index push_tokens_by_user on public.push_tokens (user_id);

-- ---------------------------------------------------------- account deletion

create type public.deletion_state as enum ('requested', 'cancelled', 'completed');

/**
 * §S22 — account deletion.
 *
 * A request, not the deletion itself. §S22: "Sign out immediately after confirmed deletion or
 * scheduled deletion, according to the approved retention policy" — and that policy is a §22
 * founder decision that does not exist yet. So this records the request, moves the account to
 * `deletion_pending`, and signs the person out; what happens at `scheduled_for` is deliberately
 * not implemented, because erasure written against a guessed policy is not reversible.
 *
 * The partial unique index means a second tap finds the existing request rather than creating
 * a duplicate — the same idempotency §S16 required of submission.
 */
create table public.deletion_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (user_id) on delete cascade,
  state public.deletion_state not null default 'requested',
  reason text,
  requested_at timestamptz not null default now(),
  scheduled_for timestamptz not null default (now() + interval '30 days'),
  completed_at timestamptz,

  constraint deletion_reason_length check (reason is null or char_length(reason) <= 1000)
);

create unique index deletion_requests_one_open
  on public.deletion_requests (user_id)
  where state = 'requested';

-- ------------------------------------------------------------- referral codes

/**
 * §S19 — "Personal referral code, remaining invitations, share sheet and redemption count."
 *
 * Referral invitations are ordinary rows in `invites` with `owner_user_id` set, so redemption,
 * capacity and the concurrency guarantees proved in Milestone 1 are reused rather than
 * reimplemented.
 *
 * One thing has to change to make S19 possible, and it is a real trade-off. Milestone 1 stores
 * only `code_hash`, so "a leaked backup yields no working invitations". But a referral code
 * must be shown to its owner, repeatedly, on every visit to S19 — and a hash cannot be shown.
 *
 * So `code_plain` exists for referral invites only, readable exclusively by the person whose
 * code it is. Founder and campaign codes stay hash-only and are unaffected. The property that
 * weakens is narrow: a database leak would expose codes that let a stranger *register*, which
 * still leaves them facing manual review (§15.2) — not codes that grant access to anything.
 * Recorded in ADR-0006 rather than made silently.
 */
alter table public.invites add column if not exists code_plain text;

comment on column public.invites.code_plain is
  'Referral codes only (§S19), where the owner must be able to read their own code back.
   Null for founder and campaign invites, which remain hash-only. See ADR-0006.';

alter table public.invites
  add constraint code_plain_only_for_referrals
  check (code_plain is null or owner_user_id is not null);
